### ISSUE TITLE
Obsidian support

### ISSUE THREAD

**Issue by davecan** [chrisgrieser/pandoc_alfred#1]
Hi, interesting workflow. Is it possible to expand this to include Obsidian since it writes natively in Markdown? Obsidian exposes an x-callback API for a few key functions and has a plugin API as well.

**Comment by chrisgrieser** [comment]
Thanks. As the workflow works on any markdown file, you can basically already write in Obsidian and run the workflow on the generated markdown file.

What could be done is implementing the hotkey functionality for Obsidian. I'll take a look whether this is possible when I have the time, but anyone already familiar with the Obsidian API is welcome to make a commit for that.

**Comment by chrisgrieser** [comment]
So I finally looked into it and it seems there is no reliable and way of determining the currently open file in Obsidian programmatically. However, you can reveal the markdown file in Finder and then just use the Hotkey.

Alternatively, you can also use the [Pandoc-Plugin for Obsidian](https://github.com/OliverBalfour/obsidian-pandoc).

**Comment by chrisgrieser** [comment]
The missing feature has been requested in the Obsidian Forum. As soon as Obsidian implements the option to copy the absolute path, I'll ass the feature. https://forum.obsidian.md/t/expand-copy-file-path-with-format-options/5737

**Comment by chrisgrieser** [comment]
@davecan Oh well, I found a hacky workaround to be able to implement the hotkey use from Obsidian anyway. It is therefore now [implemented in releasee 3.8](https://github.com/chrisgrieser/pandoc_alfred/releases/tag/3.8). However, as it is a hacky workaround, it requires some (very minor) setup, described [here in the documentation](https://www.notion.so/chrisgrieser/Pandoc-Suite-for-Citations-and-Bibliographies-in-Markdown-4de4bd634ceb4533a1add8b105a487b1#379bf518f185417097eafa8f528e4cf5).
