### ISSUE TITLE
Multiple bibtex libraries

### ISSUE THREAD

**Issue by manuelhubacher** [chrisgrieser/pandoc_alfred#2]
Hey, @chrisgrieser, thanks for this handy workflow. The new citation picker is especially great. 👍 

Maybe it is just me but there seems to be no way to use more than one bibtex library. It'd be great for my use case (one personal library and one group library), if I could include multiple libraries.

**Comment by chrisgrieser** [comment]
Thanks!

What exactly is the use case that you have in mind? Do you want to regularly switch between two libraries as you work on two projects in parallel? Or do you mean using citations from two libraries for the same project/document?

**Comment by chrisgrieser** [comment]
In case it is the latter, that is easy to implement, so I just added it to the [3.1 release](https://github.com/chrisgrieser/pandoc_alfred/releases/tag/3.1). :)

**Comment by manuelhubacher** [comment]
Exactly, I‘d like to use citations from two libraries in one project/document. So it is fantastic that you added this feature to 3.1.

**Comment by chrisgrieser** [comment]
I noticed that the second library is considered in the pandoc conversion, but not used by the new citation picker. I fixed this in [release 3.7](https://github.com/chrisgrieser/pandoc_alfred/releases/tag/3.7), now the citation picker looks for references at both libraries.
