### ISSUE TITLE
How to translate bibliography to citekeys in BibTeX?

### ISSUE THREAD

**Issue by secondbrain-note** [chrisgrieser/pandoc_alfred#5]
Hello Chris, I really appreciate your work on improving the academic workflow, and I am also using this.
A few days ago, I came up with an idea of whether we can try the other way to use the citations. It has nothing to the workflow, I just want to discuss it with someone who is a power user in academic workflow.

In our writing workflow, we cite a reference and use the citekey of it from the BibTeX and thus make a bibliography of an article.
But,  I want to make some books that have different sections and already have a bibliography in each section into Obsidian to find the relation of different parts through bi-directional links. In that case, I want to translate the bibliography into citekeys in a BibTeX file ( would be better to become references in zotero or Bibdesk). Is there any way to do that? In Obsidian or must write some scripts?
I wish you can get my point, if not, I can make a flowchart later.
Thank you for reading my post.

**Comment by chrisgrieser** [comment]
Hi, what you describe sounds interesting, but I think I indeed would need flowcharts or something to follow. 

Also, a github issue is not really the best place to discuss this. Why don't you open an issue in the obsidian forum or ask in the #academia channel of Obsidian's discord server?

**Comment by secondbrain-note** [comment]
I don't have an account for obsidian's discord, will have a try. Thank you for your advice.
